language: cpp
os: linux
dist: bionic
before_script:
- echo "deb http://archive.ubuntu.com/ubuntu xenial main universe" | sudo tee -a /etc/apt/sources.list
- sudo apt-get update -qq
- sudo apt-get install cmake libgtest-dev
- sudo apt-get install doxygen
- sudo apt-get install graphviz
- sudo apt-get install libx11-dev
- sudo apt-get install libopenblas-dev -y -qq

- wget http://dlib.net/files/dlib-19.19.tar.bz2
- tar xvf dlib-19.19.tar.bz2
- cd dlib-19.19/
- mkdir build
- cd build
- cmake ..
- sudo env "PATH=$PATH" cmake --build . --target install

- cd /usr/src/gtest
- sudo cmake CMakeLists.txt
- sudo make
- sudo cp *.a /usr/lib
- cd $TRAVIS_BUILD_DIR
script:
- cmake .
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package
- doxygen Doxyfile
deploy:
- provider: script
  skip_cleanup: true
  script:
    - curl -T realty-1.1.$TRAVIS_BUILD_NUMBER-Linux.deb -uperepiskass:$BINTRAY_API_KEY "https://api.bintray.com/content/perepiskass/Dlib/realty/$TRAVIS_BUILD_NUMBER/realty-1.1.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
- provider: pages
  skip_cleanup: true
  token: $GITHUB_TOKEN
  keep_history: true
  local_dir: html
  on: master